export const DATA_CATEGORY_HEADERS = [
  { name: 'Id', accesor: 'id' },
  { name: 'Ejercicios', accesor: 'ejercicios' },
  { name: 'Dificultad', accesor: 'dificultad' },
  { name: 'Estado', accesor: 'estado' },
  { name: 'Acciones', accesor: 'acciones' },
];

export const DATA_CATEGORY_PROBLEMS = [
  {
    id: 11,
    name: 'Introducción',
    image: 'assets/images/problems/intProgramacion.jpg',
    problems: [
      {
        id: '001',
        ejercicios: 'Resuelto 54 personas',
        ejerciciosT: 'HolaMundo',
        dificultad: 'Fácil',
        estado: 'Público',
        acciones: [
          { value: 'assets/images/crud/lapiz.png', event: 'edit' },
          { value: 'assets/images/crud/eliminar.png', event: 'delete' },
        ],
      },
      {
        id: '002',
        ejercicios: 'Resuelto 30 personas',
        ejerciciosT: 'String',
        dificultad: 'Fácil',
        estado: 'Privado',
        acciones: [
          { value: 'assets/images/crud/lapiz.png', event: 'edit' },
          { value: 'assets/images/crud/eliminar.png', event: 'delete' },
        ],
      },
      {
        id: '003',
        ejercicios: 'Resuelto 25 personas',
        ejerciciosT: 'Ingrese número',
        dificultad: 'Fácil',
        estado: 'Privado',
        acciones: [
          { value: 'assets/images/crud/lapiz.png', event: 'edit' },
          { value: 'assets/images/crud/eliminar.png', event: 'delete' },
        ],
      },
      {
        id: '004',
        ejercicios: 'Resuelto 40 personas',
        ejerciciosT: 'While-String',
        dificultad: 'Dificil',
        estado: 'Privado',
        acciones: [
          { value: 'assets/images/crud/lapiz.png', event: 'edit' },
          { value: 'assets/images/crud/eliminar.png', event: 'delete' },
        ],
      },
      {
        id: '005',
        ejercicios: 'Resuelto 15 personas',
        ejerciciosT: 'If-números',
        dificultad: 'Medio',
        estado: 'Público',
        acciones: [
          { value: 'assets/images/crud/lapiz.png', event: 'edit' },
          { value: 'assets/images/crud/eliminar.png', event: 'delete' },
        ],
      },
      {
        id: '006',
        ejercicios: 'Resuelto 5 personas',
        ejerciciosT: 'Contar números',
        dificultad: 'Fácil',
        estado: 'Público',
        acciones: [
          { value: 'assets/images/crud/lapiz.png', event: 'edit' },
          { value: 'assets/images/crud/eliminar.png', event: 'delete' },
        ],
      },
    ],
  },
  {
    id: 1,
    name: 'Búsqueda',
    image: 'assets/images/problems/busqueda.jpg',
    problems: [
      {
        id: '001',
        ejercicios: 'Resuelto 54 personas',
        ejerciciosT: 'HolaMundo',
        dificultad: 'Fácil',
        estado: 'Público',
        acciones: [
          { value: 'assets/images/crud/lapiz.png', event: 'edit' },
          { value: 'assets/images/crud/eliminar.png', event: 'delete' },
        ],
      },
      {
        id: '002',
        ejercicios: 'Resuelto 30 personas',
        ejerciciosT: 'String',
        dificultad: 'Fácil',
        estado: 'Privado',
        acciones: [
          { value: 'assets/images/crud/lapiz.png', event: 'edit' },
          { value: 'assets/images/crud/eliminar.png', event: 'delete' },
        ],
      },
      {
        id: '003',
        ejercicios: 'Resuelto 25 personas',
        ejerciciosT: 'Ingrese número',
        dificultad: 'Fácil',
        estado: 'Privado',
        acciones: [
          { value: 'assets/images/crud/lapiz.png', event: 'edit' },
          { value: 'assets/images/crud/eliminar.png', event: 'delete' },
        ],
      },
      {
        id: '004',
        ejercicios: 'Resuelto 40 personas',
        ejerciciosT: 'While-String',
        dificultad: 'Dificil',
        estado: 'Privado',
        acciones: [
          { value: 'assets/images/crud/lapiz.png', event: 'edit' },
          { value: 'assets/images/crud/eliminar.png', event: 'delete' },
        ],
      },
      {
        id: '005',
        ejercicios: 'Resuelto 15 personas',
        ejerciciosT: 'If-números',
        dificultad: 'Medio',
        estado: 'Público',
        acciones: [
          { value: 'assets/images/crud/lapiz.png', event: 'edit' },
          { value: 'assets/images/crud/eliminar.png', event: 'delete' },
        ],
      },
      {
        id: '006',
        ejercicios: 'Resuelto 5 personas',
        ejerciciosT: 'Contar números',
        dificultad: 'Fácil',
        estado: 'Público',
        acciones: [
          { value: 'assets/images/crud/lapiz.png', event: 'edit' },
          { value: 'assets/images/crud/eliminar.png', event: 'delete' },
        ],
      },
    ],
  },
  {
    id: 2,
    name: 'Estructura de datos',
    image: 'assets/images/problems/structure.jpg',
    problems: [
      {
        id: '001',
        ejercicios: 'Resuelto 54 personas',
        ejerciciosT: 'HolaMundo',
        dificultad: 'Fácil',
        estado: 'Público',
        acciones: [
          { value: 'assets/images/crud/lapiz.png', event: 'edit' },
          { value: 'assets/images/crud/eliminar.png', event: 'delete' },
        ],
      },
      {
        id: '002',
        ejercicios: 'Resuelto 30 personas',
        ejerciciosT: 'String',
        dificultad: 'Fácil',
        estado: 'Privado',
        acciones: [
          { value: 'assets/images/crud/lapiz.png', event: 'edit' },
          { value: 'assets/images/crud/eliminar.png', event: 'delete' },
        ],
      },
      {
        id: '003',
        ejercicios: 'Resuelto 25 personas',
        ejerciciosT: 'Ingrese número',
        dificultad: 'Fácil',
        estado: 'Privado',
        acciones: [
          { value: 'assets/images/crud/lapiz.png', event: 'edit' },
          { value: 'assets/images/crud/eliminar.png', event: 'delete' },
        ],
      },
      {
        id: '004',
        ejercicios: 'Resuelto 40 personas',
        ejerciciosT: 'While-String',
        dificultad: 'Dificil',
        estado: 'Privado',
        acciones: [
          { value: 'assets/images/crud/lapiz.png', event: 'edit' },
          { value: 'assets/images/crud/eliminar.png', event: 'delete' },
        ],
      },
      {
        id: '005',
        ejercicios: 'Resuelto 15 personas',
        ejerciciosT: 'If-números',
        dificultad: 'Medio',
        estado: 'Público',
        acciones: [
          { value: 'assets/images/crud/lapiz.png', event: 'edit' },
          { value: 'assets/images/crud/eliminar.png', event: 'delete' },
        ],
      },
      {
        id: '006',
        ejercicios: 'Resuelto 5 personas',
        ejerciciosT: 'Contar números',
        dificultad: 'Fácil',
        estado: 'Público',
        acciones: [
          { value: 'assets/images/crud/lapiz.png', event: 'edit' },
          { value: 'assets/images/crud/eliminar.png', event: 'delete' },
        ],
      },
    ],
  },
  {
    id: 3,
    name: 'Divide y vénceras',
    image: 'assets/images/problems/divideYVenceras.png',
    problems: [
      {
        id: '001',
        ejercicios: 'Resuelto 54 personas',
        ejerciciosT: 'HolaMundo',
        dificultad: 'Fácil',
        estado: 'Público',
        acciones: [
          { value: 'assets/images/crud/lapiz.png', event: 'edit' },
          { value: 'assets/images/crud/eliminar.png', event: 'delete' },
        ],
      },
      {
        id: '002',
        ejercicios: 'Resuelto 30 personas',
        ejerciciosT: 'String',
        dificultad: 'Fácil',
        estado: 'Privado',
        acciones: [
          { value: 'assets/images/crud/lapiz.png', event: 'edit' },
          { value: 'assets/images/crud/eliminar.png', event: 'delete' },
        ],
      },
      {
        id: '003',
        ejercicios: 'Resuelto 25 personas',
        ejerciciosT: 'Ingrese número',
        dificultad: 'Fácil',
        estado: 'Privado',
        acciones: [
          { value: 'assets/images/crud/lapiz.png', event: 'edit' },
          { value: 'assets/images/crud/eliminar.png', event: 'delete' },
        ],
      },
      {
        id: '004',
        ejercicios: 'Resuelto 40 personas',
        ejerciciosT: 'While-String',
        dificultad: 'Dificil',
        estado: 'Privado',
        acciones: [
          { value: 'assets/images/crud/lapiz.png', event: 'edit' },
          { value: 'assets/images/crud/eliminar.png', event: 'delete' },
        ],
      },
      {
        id: '005',
        ejercicios: 'Resuelto 15 personas',
        ejerciciosT: 'If-números',
        dificultad: 'Medio',
        estado: 'Público',
        acciones: [
          { value: 'assets/images/crud/lapiz.png', event: 'edit' },
          { value: 'assets/images/crud/eliminar.png', event: 'delete' },
        ],
      },
      {
        id: '006',
        ejercicios: 'Resuelto 5 personas',
        ejerciciosT: 'Contar números',
        dificultad: 'Fácil',
        estado: 'Público',
        acciones: [
          { value: 'assets/images/crud/lapiz.png', event: 'edit' },
          { value: 'assets/images/crud/eliminar.png', event: 'delete' },
        ],
      },
    ],
  },
  {
    id: 4,
    name: 'Matemáticas',
    image: 'assets/images/problems/matematicas.jpg',
    problems: [
      {
        id: '001',
        ejercicios: 'Resuelto 54 personas',
        ejerciciosT: 'HolaMundo',
        dificultad: 'Fácil',
        estado: 'Público',
        acciones: [
          { value: 'assets/images/crud/lapiz.png', event: 'edit' },
          { value: 'assets/images/crud/eliminar.png', event: 'delete' },
        ],
      },
      {
        id: '002',
        ejercicios: 'Resuelto 30 personas',
        ejerciciosT: 'String',
        dificultad: 'Fácil',
        estado: 'Privado',
        acciones: [
          { value: 'assets/images/crud/lapiz.png', event: 'edit' },
          { value: 'assets/images/crud/eliminar.png', event: 'delete' },
        ],
      },
      {
        id: '003',
        ejercicios: 'Resuelto 25 personas',
        ejerciciosT: 'Ingrese número',
        dificultad: 'Fácil',
        estado: 'Privado',
        acciones: [
          { value: 'assets/images/crud/lapiz.png', event: 'edit' },
          { value: 'assets/images/crud/eliminar.png', event: 'delete' },
        ],
      },
      {
        id: '004',
        ejercicios: 'Resuelto 40 personas',
        ejerciciosT: 'While-String',
        dificultad: 'Dificil',
        estado: 'Privado',
        acciones: [
          { value: 'assets/images/crud/lapiz.png', event: 'edit' },
          { value: 'assets/images/crud/eliminar.png', event: 'delete' },
        ],
      },
      {
        id: '005',
        ejercicios: 'Resuelto 15 personas',
        ejerciciosT: 'If-números',
        dificultad: 'Medio',
        estado: 'Público',
        acciones: [
          { value: 'assets/images/crud/lapiz.png', event: 'edit' },
          { value: 'assets/images/crud/eliminar.png', event: 'delete' },
        ],
      },
      {
        id: '006',
        ejercicios: 'Resuelto 5 personas',
        ejerciciosT: 'Contar números',
        dificultad: 'Fácil',
        estado: 'Público',
        acciones: [
          { value: 'assets/images/crud/lapiz.png', event: 'edit' },
          { value: 'assets/images/crud/eliminar.png', event: 'delete' },
        ],
      },
    ],
  },

  {
    id: 5,
    name: 'Matrices',
    image: 'assets/images/problems/matriz.png',
    problems: [
      {
        id: '001',
        ejercicios: 'Resuelto 54 personas',
        ejerciciosT: 'HolaMundo',
        dificultad: 'Fácil',
        estado: 'Público',
        acciones: [
          { value: 'assets/images/crud/lapiz.png', event: 'edit' },
          { value: 'assets/images/crud/eliminar.png', event: 'delete' },
        ],
      },
      {
        id: '002',
        ejercicios: 'Resuelto 30 personas',
        ejerciciosT: 'String',
        dificultad: 'Fácil',
        estado: 'Privado',
        acciones: [
          { value: 'assets/images/crud/lapiz.png', event: 'edit' },
          { value: 'assets/images/crud/eliminar.png', event: 'delete' },
        ],
      },
      {
        id: '003',
        ejercicios: 'Resuelto 25 personas',
        ejerciciosT: 'Ingrese número',
        dificultad: 'Fácil',
        estado: 'Privado',
        acciones: [
          { value: 'assets/images/crud/lapiz.png', event: 'edit' },
          { value: 'assets/images/crud/eliminar.png', event: 'delete' },
        ],
      },
      {
        id: '004',
        ejercicios: 'Resuelto 40 personas',
        ejerciciosT: 'While-String',
        dificultad: 'Dificil',
        estado: 'Privado',
        acciones: [
          { value: 'assets/images/crud/lapiz.png', event: 'edit' },
          { value: 'assets/images/crud/eliminar.png', event: 'delete' },
        ],
      },
      {
        id: '005',
        ejercicios: 'Resuelto 15 personas',
        ejerciciosT: 'If-números',
        dificultad: 'Medio',
        estado: 'Público',
        acciones: [
          { value: 'assets/images/crud/lapiz.png', event: 'edit' },
          { value: 'assets/images/crud/eliminar.png', event: 'delete' },
        ],
      },
      {
        id: '006',
        ejercicios: 'Resuelto 5 personas',
        ejerciciosT: 'Contar números',
        dificultad: 'Fácil',
        estado: 'Público',
        acciones: [
          { value: 'assets/images/crud/lapiz.png', event: 'edit' },
          { value: 'assets/images/crud/eliminar.png', event: 'delete' },
        ],
      },
    ],
  },

  {
    id: 6,
    name: 'Gráfos',
    image: 'assets/images/problems/graph.png',
    problems: [
      {
        id: '001',
        ejercicios: 'Resuelto 54 personas',
        ejerciciosT: 'HolaMundo',
        dificultad: 'Fácil',
        estado: 'Público',
        acciones: [
          { value: 'assets/images/crud/lapiz.png', event: 'edit' },
          { value: 'assets/images/crud/eliminar.png', event: 'delete' },
        ],
      },
      {
        id: '002',
        ejercicios: 'Resuelto 30 personas',
        ejerciciosT: 'String',
        dificultad: 'Fácil',
        estado: 'Privado',
        acciones: [
          { value: 'assets/images/crud/lapiz.png', event: 'edit' },
          { value: 'assets/images/crud/eliminar.png', event: 'delete' },
        ],
      },
      {
        id: '003',
        ejercicios: 'Resuelto 25 personas',
        ejerciciosT: 'Ingrese número',
        dificultad: 'Fácil',
        estado: 'Privado',
        acciones: [
          { value: 'assets/images/crud/lapiz.png', event: 'edit' },
          { value: 'assets/images/crud/eliminar.png', event: 'delete' },
        ],
      },
      {
        id: '004',
        ejercicios: 'Resuelto 40 personas',
        ejerciciosT: 'While-String',
        dificultad: 'Dificil',
        estado: 'Privado',
        acciones: [
          { value: 'assets/images/crud/lapiz.png', event: 'edit' },
          { value: 'assets/images/crud/eliminar.png', event: 'delete' },
        ],
      },
      {
        id: '005',
        ejercicios: 'Resuelto 15 personas',
        ejerciciosT: 'If-números',
        dificultad: 'Medio',
        estado: 'Público',
        acciones: [
          { value: 'assets/images/crud/lapiz.png', event: 'edit' },
          { value: 'assets/images/crud/eliminar.png', event: 'delete' },
        ],
      },
      {
        id: '006',
        ejercicios: 'Resuelto 5 personas',
        ejerciciosT: 'Contar números',
        dificultad: 'Fácil',
        estado: 'Público',
        acciones: [
          { value: 'assets/images/crud/lapiz.png', event: 'edit' },
          { value: 'assets/images/crud/eliminar.png', event: 'delete' },
        ],
      },
    ],
  },

  {
    id: 7,
    name: 'Téoria de juegos',
    image: 'assets/images/problems/teoriaJuegos.jpg',
    problems: [
      {
        id: '001',
        ejercicios: 'Resuelto 54 personas',
        ejerciciosT: 'HolaMundo',
        dificultad: 'Fácil',
        estado: 'Público',
        acciones: [
          { value: 'assets/images/crud/lapiz.png', event: 'edit' },
          { value: 'assets/images/crud/eliminar.png', event: 'delete' },
        ],
      },
      {
        id: '002',
        ejercicios: 'Resuelto 30 personas',
        ejerciciosT: 'String',
        dificultad: 'Fácil',
        estado: 'Privado',
        acciones: [
          { value: 'assets/images/crud/lapiz.png', event: 'edit' },
          { value: 'assets/images/crud/eliminar.png', event: 'delete' },
        ],
      },
      {
        id: '003',
        ejercicios: 'Resuelto 25 personas',
        ejerciciosT: 'Ingrese número',
        dificultad: 'Fácil',
        estado: 'Privado',
        acciones: [
          { value: 'assets/images/crud/lapiz.png', event: 'edit' },
          { value: 'assets/images/crud/eliminar.png', event: 'delete' },
        ],
      },
      {
        id: '004',
        ejercicios: 'Resuelto 40 personas',
        ejerciciosT: 'While-String',
        dificultad: 'Dificil',
        estado: 'Privado',
        acciones: [
          { value: 'assets/images/crud/lapiz.png', event: 'edit' },
          { value: 'assets/images/crud/eliminar.png', event: 'delete' },
        ],
      },
      {
        id: '005',
        ejercicios: 'Resuelto 15 personas',
        ejerciciosT: 'If-números',
        dificultad: 'Medio',
        estado: 'Público',
        acciones: [
          { value: 'assets/images/crud/lapiz.png', event: 'edit' },
          { value: 'assets/images/crud/eliminar.png', event: 'delete' },
        ],
      },
      {
        id: '006',
        ejercicios: 'Resuelto 5 personas',
        ejerciciosT: 'Contar números',
        dificultad: 'Fácil',
        estado: 'Público',
        acciones: [
          { value: 'assets/images/crud/lapiz.png', event: 'edit' },
          { value: 'assets/images/crud/eliminar.png', event: 'delete' },
        ],
      },
    ],
  },
  {
    id: 8,
    name: 'String',
    image: 'assets/images/problems/string.jpg',
    problems: [
      {
        id: '001',
        ejercicios: 'Resuelto 54 personas',
        ejerciciosT: 'HolaMundo',
        dificultad: 'Fácil',
        estado: 'Público',
        acciones: [
          { value: 'assets/images/crud/lapiz.png', event: 'edit' },
          { value: 'assets/images/crud/eliminar.png', event: 'delete' },
        ],
      },
      {
        id: '002',
        ejercicios: 'Resuelto 30 personas',
        ejerciciosT: 'String',
        dificultad: 'Fácil',
        estado: 'Privado',
        acciones: [
          { value: 'assets/images/crud/lapiz.png', event: 'edit' },
          { value: 'assets/images/crud/eliminar.png', event: 'delete' },
        ],
      },
      {
        id: '003',
        ejercicios: 'Resuelto 25 personas',
        ejerciciosT: 'Ingrese número',
        dificultad: 'Fácil',
        estado: 'Privado',
        acciones: [
          { value: 'assets/images/crud/lapiz.png', event: 'edit' },
          { value: 'assets/images/crud/eliminar.png', event: 'delete' },
        ],
      },
      {
        id: '004',
        ejercicios: 'Resuelto 40 personas',
        ejerciciosT: 'While-String',
        dificultad: 'Dificil',
        estado: 'Privado',
        acciones: [
          { value: 'assets/images/crud/lapiz.png', event: 'edit' },
          { value: 'assets/images/crud/eliminar.png', event: 'delete' },
        ],
      },
      {
        id: '005',
        ejercicios: 'Resuelto 15 personas',
        ejerciciosT: 'If-números',
        dificultad: 'Medio',
        estado: 'Público',
        acciones: [
          { value: 'assets/images/crud/lapiz.png', event: 'edit' },
          { value: 'assets/images/crud/eliminar.png', event: 'delete' },
        ],
      },
      {
        id: '006',
        ejercicios: 'Resuelto 5 personas',
        ejerciciosT: 'Contar números',
        dificultad: 'Fácil',
        estado: 'Público',
        acciones: [
          { value: 'assets/images/crud/lapiz.png', event: 'edit' },
          { value: 'assets/images/crud/eliminar.png', event: 'delete' },
        ],
      },
    ],
  },
];
export const DATA_CATEGORY_HEADERS_P = [
  { name: 'Id', accesor: 'id' },
  { name: 'Ejercicios', accesor: 'ejercicios' },
  { name: 'Dificultad', accesor: 'dificultad' },
  { name: 'Estado', accesor: 'estado' },
];
export const DATA_CATEGORY_PROBLEMS_P = [
  {
    id: 11,
    name: 'Introducción',
    image: 'assets/images/problems/intProgramacion.jpg',
    problems: [
      {
        id: '001',
        ejercicios: 'Resuelto 54 personas',
        ejerciciosT: 'HolaMundo',
        dificultad: 'Fácil',
        estado: 'Resolver',
      },
      {
        id: '002',
        ejercicios: 'Resuelto 30 personas',
        ejerciciosT: 'String',
        dificultad: 'Fácil',
        estado: 'Resuelto',
      },
      {
        id: '003',
        ejercicios: 'Resuelto 25 personas',
        ejerciciosT: 'Ingrese número',
        dificultad: 'Fácil',
        estado: 'Resuelto',
      },
      {
        id: '004',
        ejercicios: 'Resuelto 40 personas',
        ejerciciosT: 'While-String',
        dificultad: 'Dificil',
        estado: 'Resuelto',
      },
      {
        id: '005',
        ejercicios: 'Resuelto 15 personas',
        ejerciciosT: 'If-números',
        dificultad: 'Medio',
        estado: 'Resolver',
      },
      {
        id: '006',
        ejercicios: 'Resuelto 5 personas',
        ejerciciosT: 'Contar números',
        dificultad: 'Fácil',
        estado: 'Resolver',
      },
    ],
  },
  {
    id: 1,
    name: 'Búsqueda',
    image: 'assets/images/problems/busqueda.jpg',
    problems: [
      {
        id: '001',
        ejercicios: 'Resuelto 54 personas',
        ejerciciosT: 'HolaMundo',
        dificultad: 'Fácil',
        estado: 'Resolver',
      },
      {
        id: '002',
        ejercicios: 'Resuelto 30 personas',
        ejerciciosT: 'String',
        dificultad: 'Fácil',
        estado: 'Resuelto',
      },
      {
        id: '003',
        ejercicios: 'Resuelto 25 personas',
        ejerciciosT: 'Ingrese número',
        dificultad: 'Fácil',
        estado: 'Resuelto',
      },
      {
        id: '004',
        ejercicios: 'Resuelto 40 personas',
        ejerciciosT: 'While-String',
        dificultad: 'Dificil',
        estado: 'Resuelto',
      },
      {
        id: '005',
        ejercicios: 'Resuelto 15 personas',
        ejerciciosT: 'If-números',
        dificultad: 'Medio',
        estado: 'Resolver',
      },
      {
        id: '006',
        ejercicios: 'Resuelto 5 personas',
        ejerciciosT: 'Contar números',
        dificultad: 'Fácil',
        estado: 'Resolver',
      },
    ],
  },
  {
    id: 2,
    name: 'Estructura de datos',
    image: 'assets/images/problems/structure.jpg',
    problems: [
      {
        id: '001',
        ejercicios: 'Resuelto 54 personas',
        ejerciciosT: 'HolaMundo',
        dificultad: 'Fácil',
        estado: 'Resolver',
      },
      {
        id: '002',
        ejercicios: 'Resuelto 30 personas',
        ejerciciosT: 'String',
        dificultad: 'Fácil',
        estado: 'Resuelto',
      },
      {
        id: '003',
        ejercicios: 'Resuelto 25 personas',
        ejerciciosT: 'Ingrese número',
        dificultad: 'Fácil',
        estado: 'Resuelto',
      },
      {
        id: '004',
        ejercicios: 'Resuelto 40 personas',
        ejerciciosT: 'While-String',
        dificultad: 'Dificil',
        estado: 'Resuelto',
      },
      {
        id: '005',
        ejercicios: 'Resuelto 15 personas',
        ejerciciosT: 'If-números',
        dificultad: 'Medio',
        estado: 'Resolver',
      },
      {
        id: '006',
        ejercicios: 'Resuelto 5 personas',
        ejerciciosT: 'Contar números',
        dificultad: 'Fácil',
        estado: 'Resolver',
      },
    ],
  },
  {
    id: 3,
    name: 'Divide y vénceras',
    image: 'assets/images/problems/divideYVenceras.png',
    problems: [
      {
        id: '001',
        ejercicios: 'Resuelto 54 personas',
        ejerciciosT: 'HolaMundo',
        dificultad: 'Fácil',
        estado: 'Resolver',
      },
      {
        id: '002',
        ejercicios: 'Resuelto 30 personas',
        ejerciciosT: 'String',
        dificultad: 'Fácil',
        estado: 'Resuelto',
      },
      {
        id: '003',
        ejercicios: 'Resuelto 25 personas',
        ejerciciosT: 'Ingrese número',
        dificultad: 'Fácil',
        estado: 'Resuelto',
      },
      {
        id: '004',
        ejercicios: 'Resuelto 40 personas',
        ejerciciosT: 'While-String',
        dificultad: 'Dificil',
        estado: 'Resuelto',
      },
      {
        id: '005',
        ejercicios: 'Resuelto 15 personas',
        ejerciciosT: 'If-números',
        dificultad: 'Medio',
        estado: 'Resolver',
      },
      {
        id: '006',
        ejercicios: 'Resuelto 5 personas',
        ejerciciosT: 'Contar números',
        dificultad: 'Fácil',
        estado: 'Resolver',
      },
    ],
  },
  {
    id: 4,
    name: 'Matemáticas',
    image: 'assets/images/problems/matematicas.jpg',
    problems: [
      {
        id: '001',
        ejercicios: 'Resuelto 54 personas',
        ejerciciosT: 'HolaMundo',
        dificultad: 'Fácil',
        estado: 'Resolver',
      },
      {
        id: '002',
        ejercicios: 'Resuelto 30 personas',
        ejerciciosT: 'String',
        dificultad: 'Fácil',
        estado: 'Resuelto',
      },
      {
        id: '003',
        ejercicios: 'Resuelto 25 personas',
        ejerciciosT: 'Ingrese número',
        dificultad: 'Fácil',
        estado: 'Resuelto',
      },
      {
        id: '004',
        ejercicios: 'Resuelto 40 personas',
        ejerciciosT: 'While-String',
        dificultad: 'Dificil',
        estado: 'Resuelto',
      },
      {
        id: '005',
        ejercicios: 'Resuelto 15 personas',
        ejerciciosT: 'If-números',
        dificultad: 'Medio',
        estado: 'Resolver',
      },
      {
        id: '006',
        ejercicios: 'Resuelto 5 personas',
        ejerciciosT: 'Contar números',
        dificultad: 'Fácil',
        estado: 'Resolver',
      },
    ],
  },

  {
    id: 5,
    name: 'Matrices',
    image: 'assets/images/problems/matriz.png',
    problems: [
      {
        id: '001',
        ejercicios: 'Resuelto 54 personas',
        ejerciciosT: 'HolaMundo',
        dificultad: 'Fácil',
        estado: 'Resolver',
      },
      {
        id: '002',
        ejercicios: 'Resuelto 30 personas',
        ejerciciosT: 'String',
        dificultad: 'Fácil',
        estado: 'Resuelto',
      },
      {
        id: '003',
        ejercicios: 'Resuelto 25 personas',
        ejerciciosT: 'Ingrese número',
        dificultad: 'Fácil',
        estado: 'Resuelto',
      },
      {
        id: '004',
        ejercicios: 'Resuelto 40 personas',
        ejerciciosT: 'While-String',
        dificultad: 'Dificil',
        estado: 'Resuelto',
      },
      {
        id: '005',
        ejercicios: 'Resuelto 15 personas',
        ejerciciosT: 'If-números',
        dificultad: 'Medio',
        estado: 'Resolver',
      },
      {
        id: '006',
        ejercicios: 'Resuelto 5 personas',
        ejerciciosT: 'Contar números',
        dificultad: 'Fácil',
        estado: 'Resolver',
      },
    ],
  },

  {
    id: 6,
    name: 'Gráfos',
    image: 'assets/images/problems/graph.png',
    problems: [
      {
        id: '001',
        ejercicios: 'Resuelto 54 personas',
        ejerciciosT: 'HolaMundo',
        dificultad: 'Fácil',
        estado: 'Resolver',
      },
      {
        id: '002',
        ejercicios: 'Resuelto 30 personas',
        ejerciciosT: 'String',
        dificultad: 'Fácil',
        estado: 'Resuelto',
      },
      {
        id: '003',
        ejercicios: 'Resuelto 25 personas',
        ejerciciosT: 'Ingrese número',
        dificultad: 'Fácil',
        estado: 'Resuelto',
      },
      {
        id: '004',
        ejercicios: 'Resuelto 40 personas',
        ejerciciosT: 'While-String',
        dificultad: 'Dificil',
        estado: 'Resuelto',
      },
      {
        id: '005',
        ejercicios: 'Resuelto 15 personas',
        ejerciciosT: 'If-números',
        dificultad: 'Medio',
        estado: 'Resolver',
      },
      {
        id: '006',
        ejercicios: 'Resuelto 5 personas',
        ejerciciosT: 'Contar números',
        dificultad: 'Fácil',
        estado: 'Resolver',
      },
    ],
  },

  {
    id: 7,
    name: 'Téoria de juegos',
    image: 'assets/images/problems/teoriaJuegos.jpg',
    problems: [
      {
        id: '001',
        ejercicios: 'Resuelto 54 personas',
        ejerciciosT: 'HolaMundo',
        dificultad: 'Fácil',
        estado: 'Resolver',
      },
      {
        id: '002',
        ejercicios: 'Resuelto 30 personas',
        ejerciciosT: 'String',
        dificultad: 'Fácil',
        estado: 'Resuelto',
      },
      {
        id: '003',
        ejercicios: 'Resuelto 25 personas',
        ejerciciosT: 'Ingrese número',
        dificultad: 'Fácil',
        estado: 'Resuelto',
      },
      {
        id: '004',
        ejercicios: 'Resuelto 40 personas',
        ejerciciosT: 'While-String',
        dificultad: 'Dificil',
        estado: 'Resuelto',
      },
      {
        id: '005',
        ejercicios: 'Resuelto 15 personas',
        ejerciciosT: 'If-números',
        dificultad: 'Medio',
        estado: 'Resolver',
      },
      {
        id: '006',
        ejercicios: 'Resuelto 5 personas',
        ejerciciosT: 'Contar números',
        dificultad: 'Fácil',
        estado: 'Resolver',
      },
    ],
  },
  {
    id: 8,
    name: 'String',
    image: 'assets/images/problems/string.jpg',
    problems: [
      {
        id: '001',
        ejercicios: 'Resuelto 54 personas',
        ejerciciosT: 'HolaMundo',
        dificultad: 'Fácil',
        estado: 'Resolver',
      },
      {
        id: '002',
        ejercicios: 'Resuelto 30 personas',
        ejerciciosT: 'String',
        dificultad: 'Fácil',
        estado: 'Resuelto',
      },
      {
        id: '003',
        ejercicios: 'Resuelto 25 personas',
        ejerciciosT: 'Ingrese número',
        dificultad: 'Fácil',
        estado: 'Resuelto',
      },
      {
        id: '004',
        ejercicios: 'Resuelto 40 personas',
        ejerciciosT: 'While-String',
        dificultad: 'Dificil',
        estado: 'Resuelto',
      },
      {
        id: '005',
        ejercicios: 'Resuelto 15 personas',
        ejerciciosT: 'If-números',
        dificultad: 'Medio',
        estado: 'Resolver',
      },
      {
        id: '006',
        ejercicios: 'Resuelto 5 personas',
        ejerciciosT: 'Contar números',
        dificultad: 'Fácil',
        estado: 'Resolver',
      },
    ],
  },
];

export const DESCRIPTION_PROBLEM = {};
